server:
  port: 7902
spring:
  application:
    name: microservice-consumer-movie-ribbon
eureka:
  client:
    healthcheck:
        enable: true
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
microservice-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule