server:
  port: 8761
eureka:
  client:
    healthcheck:
      enable: true
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false
security:
  user:
    name: user
    password: password123
