server:
  port: 7901
spring:
  application:
    name: microservice-consumer-movie
user:
  userServicePath: http://localhost:7900/simple/
eureka:
  client:
    healthcheck:
        enable: true
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
